package se.sugarest.jane.bilder.data.types;

/**
 * This package contains the data types used to parse the JSON from FlickrAPI.
 * <p>
 * Complete Url example to request:
 * https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=[YOUR_API_KEY]&text=dog&format=json&nojsoncallback=1
 * <p>
 * Class {@link se.sugarest.jane.bilder.data.types.JSONResponse} {@link se.sugarest.jane.bilder.data.types.Photos}
 * {@link se.sugarest.jane.bilder.data.types.Photo} are automatically generated by http://www.jsonschema2pojo.org/
 * <p>
 * Created by jane on 17-11-3.
 */
